version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: affirm-mysql
    environment:
      - MYSQL_DATABASE=affirm
      - MYSQL_USER=affirm
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  redis:
    image: redis:7
    container_name: affirm-redis
    ports:
      - "6379:6379"

volumes:
  db_data:


